// colorMap.js
import { FiCheckCircle, FiAlertCircle, FiInfo } from "react-icons/fi";

export const colorMap = {
  success: {
    icon: FiCheckCircle,
    iconBg: "#16A34A",
    border: "#16A34A",
    bg: "rgba(22, 163, 74, 0.12)",
    hover: "rgba(22, 163, 74, 0.18)",
  },
  error: {
    icon: FiAlertCircle,
    iconBg: "#DC2626",
    border: "#DC2626",
    bg: "rgba(220, 38, 38, 0.12)",
    hover: "rgba(220, 38, 38, 0.18)",
  },
  warn: {
    icon: FiAlertCircle,
    iconBg: "#FACC15",
    border: "#FACC15",
    bg: "rgba(250, 204, 21, 0.12)",
    hover: "rgba(250, 204, 21, 0.18)",
  },
  info: {
    icon: FiInfo,
    iconBg: "#3B82F6",
    border: "#3B82F6",
    bg: "rgba(59, 130, 246, 0.12)",
    hover: "rgba(59, 130, 246, 0.18)",
  },
};

export const CountryOptions = [
  {
    value: "ATVPDKIKX0DER",
    label: "United States",
    code: "us",
    regionType: "NORTH_AMERICA",
  },
  {
    value: "A2EUQ1WTGCTBG2",
    label: "Canada",
    code: "ca",
    regionType: "NORTH_AMERICA",
  },
  {
    value: "A1AM78C64UM0Y8",
    label: "Mexico",
    code: "mx",
    regionType: "NORTH_AMERICA",
  },
  {
    value: "A2Q3Y263D00KWC",
    label: "Brazil",
    code: "br",
    regionType: "NORTH_AMERICA",
  },
  {
    value: "A28R8C7NBKEWEA",
    label: "Ireland",
    code: "ie",
    regionType: "EUROPE",
  },
  { value: "A1RKKUPIHCS9HS", label: "Spain", code: "es", regionType: "EUROPE" },
  {
    value: "A1F83G8C2ARO7P",
    label: "United Kingdom",
    code: "gb",
    regionType: "EUROPE",
  },
  {
    value: "A13V1IB3VIYZZH",
    label: "France",
    code: "fr",
    regionType: "EUROPE",
  },
  {
    value: "AMEN7PMS3EDWL",
    label: "Belgium",
    code: "be",
    regionType: "EUROPE",
  },
  {
    value: "A1805IZSGTT6HS",
    label: "Netherlands",
    code: "nl",
    regionType: "EUROPE",
  },
  {
    value: "A1PA6795UKMFR9",
    label: "Germany",
    code: "de",
    regionType: "EUROPE",
  },
  { value: "APJ6JRA9NG5V4", label: "Italy", code: "it", regionType: "EUROPE" },
  {
    value: "A2NODRKZP88ZB9",
    label: "Sweden",
    code: "se",
    regionType: "EUROPE",
  },
  {
    value: "A1C3SOZRARQ6R3",
    label: "Poland",
    code: "pl",
    regionType: "EUROPE",
  },
  {
    value: "A33AVAJ2PDY3EV",
    label: "Turkey",
    code: "tr",
    regionType: "EUROPE",
    value: "A33AVAJ2PDY3EV",
    label: "Turkey",
    code: "tr",
    regionType: "EUROPE",
  },
  {
    value: "A2VIGQ35RCS4UG",
    label: "United Arab Emirates",
    code: "ae",
    regionType: "UAE",
  },
  {
    value: "A19VAU5U5O7RUS",
    label: "Singapore",
    code: "sg",
    regionType: "SINGAPORE",
  },
  {
    value: "A39IBJ37TRP1C6",
    label: "Australia",
    code: "au",
    regionType: "AUSTRALIA",
  },
  { value: "A1VC38T7YXB528", label: "Japan", code: "jp", regionType: "JAPAN" },
];

export const marketplaceToCountry = {
  ATVPDKIKX0DER: "us",
  A2EUQ1WTGCTBG2: "ca",
  A1AM78C64UM0Y8: "mx",
  A2Q3Y263D00KWC: "br",
  A28R8C7NBKEWEA: "ie",
  A1RKKUPIHCS9HS: "es",
  A1F83G8C2ARO7P: "gb",
  A13V1IB3VIYZZH: "fr",
  AMEN7PMS3EDWL: "be",
  A1805IZSGTT6HS: "nl",
  A1PA6795UKMFR9: "de",
  APJ6JRA9NG5V4: "it",
  A2NODRKZP88ZB9: "se",
  AE08WJ6YKNBMC: "za",
  A1C3SOZRARQ6R3: "pl",
  ARBP9OOSHTCHU: "eg",
  A33AVAJ2PDY3EV: "tr",
  A17E79C6D8DWNP: "sa",
  A2VIGQ35RCS4UG: "ae",
  A21TJRUUN4KGV: "in",
  A19VAU5U5O7RUS: "sg",
  A39IBJ37TRP1C6: "au",
  A1VC38T7YXB528: "jp",
};
